R+ instead of R in norm def and minor typos
avivt/RL-book-overleaf pull request #7
Opened 2021-05-12 19:05 UTC by ynahum

2021-05-14 19:09 UTC, avivt requested changes

2021-05-14 19:09 UTC, avivt commented on chapter2-ddp.tex
> +\E[\Cost^\policy(\state_0)]=\sum_{\action\in \Actions_0}\cost_0(\state_0,\action)\pi
good catch. But this will be cleaner if we simply start the sum from t=0.

2021-05-14 19:09 UTC, avivt commented on chapter2-ddp.tex
> +\E^\policy_{\state_\ttime,\action_\ttime}[\cost_{\ttime}(\state_\ttime,\action_\ttime)+\Cost_{\ttime+1}(f_\ttime(\state_\ttime,\action_\ttime))]\\
I don't understand the first change.

2021-05-15 20:40 UTC, ynahum commented on chapter2-ddp.tex
> +\E[\Cost^\policy(\state_0)]=\sum_{\action\in \Actions_0}\cost_0(\state_0,\action)\pi
OK. will fix.  BTW, do we assume no cost on terminal state? as it's also not part of the sum.

2021-05-15 20:44 UTC, ynahum commented on chapter2-ddp.tex
> +\E^\policy_{\state_\ttime,\action_\ttime}[\cost_{\ttime}(\state_\ttime,\action_\ttime)+\Cost_{\ttime+1}(f_\ttime(\state_\ttime,\action_\ttime))]\\
From what I understand, the expectation is given s_t and a_t (smoothing theorem of expectations).
so it's more accurate to add both and not only s_t. The first expectation is still given s_t only.

2021-05-20 06:21 UTC, ynahum commented
Hi Aviv
Kindly reminder :)

2021-06-06 08:59 UTC, avivt commented on chapter2-ddp.tex
> +\E[\Cost^\policy(\state_0)]=\sum_{\action\in \Actions_0}\cost_0(\state_0,\action)\pi
yes, since the cost is time dependent, it does not matter.

2021-06-06 09:05 UTC, avivt commented on chapter2-ddp.tex
> +\E^\policy_{\state_\ttime,\action_\ttime}[\cost_{\ttime}(\state_\ttime,\action_\ttime)+\Cost_{\ttime+1}(f_\ttime(\state_\ttime,\action_\ttime))]\\
I think it's OK as it is. The first expectation conditions on the state, so in the second )inner) expectation the state is a constant, and we condition on the action.

2021-06-06 09:18 UTC, avivt requested changes

2021-06-06 09:18 UTC, avivt commented on chapter3-MDP-FH.tex
> +$\state\in\States/\{\state_G\}$ and action $\action\in\Actions$, while
don't need that because S is defined without s_G

2021-06-06 09:39 UTC, ynahum commented on chapter2-ddp.tex
> +\E^\policy_{\state_\ttime,\action_\ttime}[\cost_{\ttime}(\state_\ttime,\action_\ttime)+\Cost_{\ttime+1}(f_\ttime(\state_\ttime,\action_\ttime))]\\
reverted in a follow up commit

2021-06-06 09:39 UTC, ynahum commented on chapter3-MDP-FH.tex
> +$\state\in\States/\{\state_G\}$ and action $\action\in\Actions$, while
reverted in a follow up commit

2021-06-06 10:13 UTC, merged

2021-06-06 10:13 UTC, avivt commented
Thanks a lot!